<?php
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

\App\Models\Machine::where('qr_code', 'like', 'GEN-%')->delete();
echo "Old autogenerated machines deleted successfully.\n";
